### ISSUE TITLE
Host Project on Bram-Hub

### ISSUE THREAD

**Issue by jpoegs** [Bram-Hub/VisualLogic-Web#17]
@shailpatels Do you mind if I create a subdomain on Bram-Hub and host your project on Github pages?

**Comment by shailpatels** [comment]
I don't mind :)

The project doesn't have any dependencies for deployig so installing via git and pointing to `index.html` should be all you need for hosting

**Comment by jpoegs** [comment]
Done. Your project is hosted here: https://visual-logic.bram-hub.com.
